name: sensorml-pages.1

on:
  push:
    branches: [ meta-test ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Metanorma assets
        uses: cam-s-hunt/cache@patch-1

      - name: Metanorma generate site
        uses: cam-s-hunt/build-and-publish@patch-1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          agree-to-terms: true
          source-path: sensorml/standard

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
